### ISSUE TITLE
Uncaught TypeError: i.Started.toUTCString is not a function

### ISSUE THREAD

**Issue by xianhc** [MiniProfiler/dotnet#459]
I integrated swagger5.0.0 version and MiniProfiler4.1.0 version in .net core 3.1 webapi project
swagger index.html Script configuration
    <script async="async" id="mini-profiler" src="/profiler/includes.min.js?v=4.1.0+c940f0f28d"
            data-version="4.1.0+c940f0f28d" data-path="/profiler/"
            data-current-id="4ec7c742-49d4-4eaf-8281-3c1e0efa8888" data-ids="4ec7c742-49d4-4eaf-8281-3c1e0efa8888"
            data-position="Left"
            data-authorized="true" data-max-traces="5" data-toggle-shortcut="Alt+P"
            data-trivial-milliseconds="2.0" data-ignored-duplicate-execute-types="Open,OpenAsync,Close,CloseAsync">
    </script>

Pipeline middleware configuration
 services.AddMiniProfiler(options =>
            {
                options.RouteBasePath = "/profiler";
                options.PopupRenderPosition = StackExchange.Profiling.RenderPosition.Left;
                options.PopupShowTimeWithChildren = true;
            }
           ).AddEntityFramework();

Whenever an interface is called on the swagger-ui page, an error is reported
Uncaught TypeError: i.Started.toUTCString is not a function
at n.renderProfiler (includes.min.js?v=4.1.0+c940f0f28d:2)
at n.buttonShow (includes.min.js?v=4.1.0+c940f0f28d:2)
at Object.success (includes.min.js?v=4.1.0+c940f0f28d:2)
at l (includes.min.js?v=4.1.0+c940f0f28d:2)
at Object.fireWith [as resolveWith] (includes.min.js?v=4.1.0+c940f0f28d:2)
at b (includes.min.js?v=4.1.0+c940f0f28d:2)
at XMLHttpRequest.<anonymous> (includes.min.js?v=4.1.0+c940f0f28d:2)

Example JS Response
{
    "Id":"87c5f9ce-fba7-4dda-b88a-78eac1fdae79",
    "Name":"Home/test7",
    "Started":"2020-03-12 05:02:29",
    "DurationMilliseconds":174.3,
    "MachineName":"LENOVO-PC",
    "Root":Object{...},
    "User":"::1",
    "HasUserViewed":true
}

I do n’t see a small icon for adding performance monitoring in the upper left corner of the dashboard.
But you can see all monitoring history in /profiler/results-index page
How can i solve this

**Comment by sunshuai3748** [comment]
I have the same problem

**Comment by sunshuai3748** [comment]
I have fixed my problem,because i have use a convert before response ，as the code blow ：
JsonSerializerSettings setting = new JsonSerializerSettings();
            JsonConvert.DefaultSettings = new Func<JsonSerializerSettings>(() =>
            {
                  setting.DateFormatHandling = DateFormatHandling.MicrosoftDateFormat;
                  setting.DateFormatString = "yyyy-MM-dd HH:mm:ss";
                  return setting;
            });
Comment these code as a temp solution

**Comment by xianhc** [comment]
@sunshuai3748 I didn't set the response time format in the project, but still error

**Comment by xianhc** [comment]
@sunshuai3748 I tried to set the time format, but I still get errors. Is there any other possible solution?

**Comment by sunshuai3748** [comment]
@xianhc I have a stupid idea :you can start a simp project  and add code step by step from your project until the error occur

**Comment by NickCraver** [comment]
Thanks @sunshuai3748, that was hugely helpful :) Pushing a fix up now in #462 :)

**Comment by NickCraver** [comment]
This is fixed in #462 - up on MyGet now, once Dark mode is polished I'll get a NuGet version up as well.

**Comment by NickCraver** [comment]
Closing out to cleanup - expect a NuGet release likely this week.
